### ISSUE TITLE
plugin version is N/A

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/log-cache-cli#12]
After following the instructions to install the plugin, I ran the `cf plugins` command and the output is as follows:

```
plugin                 version   command name             command help
Log Cache CLI Plugin   N/A       log-meta                 Show all available meta information
Log Cache CLI Plugin   N/A       tail                     Output logs for a source-id/app
```

Also it might be worth publishing the plugin to [CF-Community](plugins.cloudfoundry.org). You would need to make a PR to [cli-plugin-repo](https://github.com/cloudfoundry/cli-plugin-repo)

**Comment by apoydence** [comment]
Good catch. We haven't made a release yet. 

I would also question the name being "Log Cache CLI Plugin". This makes for an awkward uninstall: `cf uninstall-plugin 'Log Cache CLI Plugin'`. Perhaps a more reasonable name would be `LogCache` or `log-cache`.

**Comment by wfernandes** [comment]
I suggest `log-cache` since that's the naming convention that had been proposed to the EVA team by the CLI team.

**Comment by bradylove** [comment]
@wfernandes we have added a version to the build process and that will no longer be `N/A` with our next build.

However if you follow the instructions in the README to go get the plugin it will always be `N/A` since the version is injected at build time in our CI.

The name has also been changed to `log-cache`, before you can install the new plugin you will need to run `cf uninstall-plugin "Log Cache CLI Plugin"`

**Comment by wfernandes** [comment]
@bradylove Thanks! That makes sense.
